#   execs:
#       - <exec_name_1>:
#           - args: <commandline arg_list 1> # Leave blank if no arguments
#             <optional> accel-sim-mem: <xG>
#           - args: <commandline arg_list 2>
#           ...
#       - <exec_name_2>
#           ...
#       ...
# If you have a bunch of random benchmarks in random places, then a "suite" can be just one benchmark

rodinia-3.1:
    exec_dir: "$GPUAPPS_ROOT/bin/$CUDA_VERSION/release/"
    data_dirs: "$GPUAPPS_ROOT/data_dirs/cuda/rodinia/3.1/"
    execs:
    # Memory-bound
        - nn-rodinia-3.1:
            - args:  ./data/filelist_4 -r 5 -lat 30 -lng 90
              accel-sim-mem: 4G
        - hybridsort-rodinia-3.1:
            - args:  ./data/500000.txt
              accel-sim-mem: 1G
        - bfs-rodinia-3.1:
            - args:  ./data/graph1MW_6.txt
              accel-sim-mem: 1G
    # Compute
        - gaussian-rodinia-3.1:
            - args:  -f ./data/matrix208.txt
              accel-sim-mem: 1G
        - dwt2d-rodinia-3.1:
            - args:  ./data/rgb.bmp -d 1024x1024 -f -5 -l 3
              accel-sim-mem: 1G
        - backprop-rodinia-3.1:
            - args:  65536
              accel-sim-mem: 1G
    # Both
        - particlefilter_naive-rodinia-3.1:
            - args:  -x 128 -y 128 -z 10 -np 1000
              accel-sim-mem: 1G
        - nw-rodinia-3.1:
            - args:  2048 10
              accel-sim-mem: 1G
        - b+tree-rodinia-3.1:
            - args:  file ./data/mil.txt command ./data/command.txt
              accel-sim-mem: 1G